
```{r}
library(spdep)
library(elevatr)
library(sf)
library(spData)
library(tidyverse)
library(ggplot2)
library(leaflet)
library(terra)
library(lmtest)
library(giscoR)
library(ggmap)
library(mapview)
library(tmap)
library(spatialreg)
library(hglm)
library(plot.matrix)
library(viridis)
library(sphet)
```




#Creating geometry points
```{r}
barcelona_weekdays <- read_csv("data sets/barcelona_weekdays.csv")

bar_sf <- st_as_sf(barcelona_weekdays, coords = c("lng", "lat"), crs = 4326)
bar_sf <- unique(bar_sf)
st_geometry(bar_sf)
st_crs(bar_sf)
```
```{r}
# Convert TRUE to 1 and FALSE to 0 for room_type
bar_sf$room_shared <- as.numeric(bar_sf$room_shared)

# Convert TRUE to 1 and FALSE to 0 for room_private
bar_sf$room_private <- as.numeric(bar_sf$room_private)

# Convert TRUE to 1 and FALSE to 0 for host_is_superhost
bar_sf$host_is_superhost <- as.numeric(bar_sf$host_is_superhost)

```

#searching for possible outliers
```{r}
boxplot(bar_sf$dist)
boxplot(bar_sf$attr_index)
boxplot(bar_sf$realSum)
```
# Evelation points
```{r}
bar_sf |>  get_elev_raster(z = 7,
 clip = "locations", neg_to_na = TRUE) |> 
 rast() -> bar_elev

```
```{r}
#Creating neighbouring object
(bar_sf|> knearneigh(k=7) |>
 knn2nb(row.names=bar_sf$...1, sym = TRUE) -> bar_nb)
bar_nb |> nb2lines(coords=st_geometry(bar_sf)
 ) -> bar_nb_sf
```

#visualisation
```{r}
mapview(bar_sf) + mapview(bar_nb_sf, color="red4")
```

```{r}
mapview(bar_sf, zcol="realSum")
```



## Moran I test under randomisation
```{r}

#spatial weights matrix using distance-based criterion
unb <- knn2nb(knearneigh(bar_sf, k = 7), sym = TRUE)
lw <- nb2listw(unb, style = "W")
```


```{r}
moran <- moran.test(bar_sf$guest_satisfaction_overall, listw = lw, randomisation=TRUE, alternative="two.sided")

moran

```

## Moran I test under normality

```{r}
lm_null <- lm(guest_satisfaction_overall ~ 1, data=bar_sf)
moran.test(residuals(lm_null), listw=lw,
 randomisation=FALSE, alternative="two.sided")

```


## model creation
```{r From_pre}

form_pre <- bar_sf$guest_satisfaction_overall ~ log(bar_sf$realSum) + bar_sf$host_is_superhost + bar_sf$person_capacity + bar_sf$room_type   + log(bar_sf$dist) + bar_sf$rest_index_norm + bar_sf$attr_index_norm
  
lm_obj_pre <- lm(form_pre, data=bar_sf)
moran.test(residuals(lm_obj_pre), listw=lw,
 randomisation=FALSE, alternative="two.sided")

```
```{r}

form_pre_maj <- update(form_pre, . ~. + room_private)
lm_obj_pre_maj <- lm(form_pre_maj, data=bar_sf)
summary(lm.RStests(lm_obj_pre_maj, listw=lw, test="all"))
```

#lao score

```{r} 
 summary(lm.RStests(lm_obj_pre, listw=lw, test="all"))
```



```{r}

lwB <- nb2listw(unb, style="B")
car1 <- spautolm(form_pre, data=bar_sf, listw=lwB, family="CAR")
summary(car1, Nagelkerke=TRUE)
```



# Spatial autoregressive models
```{r}
bar_sf$ranef_ml <- car1$fit$signal_stochastic
W <- as(lwB, "CsparseMatrix")
car2 <- hglm(fixed=form_pre, random= ~ 1|...1, data=bar_sf, family = gaussian(), rand.family=CAR(D=W))
car2
```


```{r}
sar1B <- spautolm(form_pre, data=bar_sf, listw=lwB, family="SAR")
summary(sar1B, Nagelkerke=TRUE)
```

```{r}
lw <- nb2listw(unb, style="W")
e <- eigenw(lw)
sar1 <- spautolm(form_pre, data=bar_sf, listw=lw, family="SAR", control=list(pre_eig=e))
summary(sar1, Nagelkerke=TRUE)
```
```{r}
form_pre <- log(bar_sf$realSum) ~ bar_sf$guest_satisfaction_overall  + bar_sf$host_is_superhost +bar_sf$attr_index  + bar_sf$person_capacity  + bar_sf$dist + bar_sf$metro_dist
```



```{R}
SEM_pre <- errorsarlm(form_pre, data=bar_sf, listw=lw, control=list(pre_eig=e))
summary(SEM_pre, Nagelkerke=TRUE)
```








```{r}
GNM_pre <- sacsarlm(form_pre, data=bar_sf, listw=lw, Durbin=update(form_pre, ~ . - Metrop), control=list(pre_eig1=e, pre_eig2=e))
SAC_pre <- sacsarlm(form_pre, data=bar_sf, listw=lw, control=list(pre_eig1=e, pre_eig2=e))
SDEM_pre <- errorsarlm(form_pre, data=bar_sf, listw=lw, Durbin=update(form_pre, ~ . - Metrop), control=list(pre_eig=e))
SDM_pre <- lagsarlm(form_pre, data=bar_sf, listw=lw, Durbin=update(form_pre, ~ . - Metrop), control=list(pre_eig=e))
SLM_pre <- lagsarlm(form_pre, data=bar_sf, listw=lw, control=list(pre_eig=e))
SLX_pre <- lmSLX(form_pre, data=bar_sf, listw=lw, Durbin=update(form_pre, ~ . - Metrop))
OLS_pre <- lm(form_pre, data=bar_sf)
```


```{r}
mlist_pre <- list(GNM=GNM_pre, SAC=SAC_pre, SDEM=SDEM_pre, SDM=SDM_pre, SLX=SLX_pre, SEM=SEM_pre, SLM=SLM_pre, OLS=OLS_pre)
m <- length(mlist_pre)
LR_pre <- matrix(NA, ncol=m, nrow=m)
colnames(LR_pre) <- rownames(LR_pre) <- names(mlist_pre)
for (j in 2:m) LR_pre[1, j] <- lrtest(mlist_pre[[1]],
    mlist_pre[[j]])[[2, "Pr(>Chisq)"]]
for (j in 6:8) LR_pre[2, j] <- lrtest(mlist_pre[[2]],
    mlist_pre[[j]])[[2, "Pr(>Chisq)"]]
for (j in c(5, 6, 8)) LR_pre[3, j] <- lrtest(mlist_pre[[3]],
    mlist_pre[[j]])[[2, "Pr(>Chisq)"]]
for (j in c(5:8)) LR_pre[4, j] <- lrtest(mlist_pre[[4]],
    mlist_pre[[j]])[[2, "Pr(>Chisq)"]]
for (i in 5:7) LR_pre[i, 8] <- lrtest(mlist_pre[[i]],
    mlist_pre[[8]])[[2, "Pr(>Chisq)"]]

```


```{r}
opar <- par(mar=c(3.1, 3.1, 3.1, 7.1), cex.axis=0.8)
plot(LR_pre, breaks=c(0, 10^-(8:0)), col=viridis, las=1)
```


#9
##1
```{r}
SAC_pre_maj <- sacsarlm(form_pre, data=bar_sf, listw=lw, control=list(pre_eig1=e, pre_eig2=e), llprof=40)
SAC_track <- capture.output(sac <- sacsarlm(form_pre, data=bar_sf, listw=lw, control=list(pre_eig1=e, pre_eig2=e), quiet=FALSE))
c(SAC_pre_maj$rho, SAC_pre_maj$lambda)
```
```{r}
c(SAC_pre_maj$rho/SAC_pre_maj$rho.se, SAC_pre_maj$lambda/SAC_pre_maj$lambda.se)
```

```{r}
m <- -matrix(SAC_pre_maj$llprof$ll, 40, 40)
con <- textConnection(SAC_track)
sac_track <- read.table(con, skip=14)
close(con)
contour(SAC_pre_maj$llprof$xseq, SAC_pre_maj$llprof$yseq, m, levels=quantile(c(m), seq(0,1,0.1)), xlab="rho", ylab="lambda", col="blue4")
abline(h=SAC_pre_maj$rho, v=SAC_pre_maj$lambda, lwd=3, col="grey")
lines(sac_track$V2, sac_track$V4, col="brown3")
```
## bayesian estimation
```{r}
set.seed(12345)
SAC_bayes <- spBreg_sac(form_pre, data=bar_sf, listw=lw, control=list(ndraw=20000L, nomit=2000L))
```

```{r}
summary(SAC_bayes[, c("rho", "lambda", "sige")])
```

```{r}
opar <- par(mfrow=c(2, 1)) 
plot(SAC_bayes[, c("rho", "lambda", "sige")], smooth=TRUE)
```
##3 GMM estimation  
```{r}
SAC_gmm <- spreg(form_pre, data=bar_sf, listw=lw, model="sarar")
c(coef(SAC_gmm)[c("lambda", "rho"),], s2=as.numeric(SAC_gmm$s2))
```
#10
###2
```{r}
lw <- nb2listw(unb, style="W")

e <- eigenw(lw)
W <- as(lw, "CsparseMatrix")
trMat <- trW(W, type="mult")
```
### Error
```{r}

SLM_pre_maj <- lagsarlm(form_pre, data=bar_sf, listw=lw, control=list(pre_eig=e))

```
```{r}
set.seed(12345)
R <- 2000
(imp_SLM_pre_maj_tr <- impacts(SLM_pre, tr=trMat, R=R))
```



#11
```{r}
OLS_pre <- lm(form_pre, data=bar_sf)
row.names(bar_sf) <- bar_sf$...1
newdata <- bar_sf
p0 <- predict(OLS_pre, newdata=newdata)
newdata$dist <- exp(log(newdata$dist)+1)
p1 <- predict(OLS_pre, newdata=newdata)
mean(p1-p0)
```



